### PR TITLE
Add several useful sensors to the exported results.

### PR DESCRIPTION
**Pull request by sofar**
This adds various printouts of the link status, connection type, the
network name, and quality metrics.

### CODE REVIEW

**Comment by sofar** [comment]
So I'm adding these so I can get a better sense of my signal strenth and possibly take action on it, like e.g. setting up something failover automation, or just kicking the netgear router in case the link is bad for more than a few minutes - rebooting has a tremendously positive effect thus far.

I can cobble up the patches to HomeAssistant, if you want.

**Comment by amelchio** [comment]
I guess writing up the documentation will be the hardest part.

Are all of these actually useful to you or are you just covering your bases? To make it easier to watch arbitrary values, I wonder if we should add a generic sensor where one can specify a field to watch.

**Comment by sofar** [comment]
I'm being fairly selective - most of these will have some function, not just to me:

- connection: obvious, is it working or not
- roaming, network provider name & link text/type: could mean roaming charges for overages, etc. May need this to enable throttling
- link quality metrics: may help determine low bandwidth and connection problems, even better point antennas or placement.

I'm using the speedtest plugin to help debug and mitigate link problems, but it's way too heavy and eats up bandwidth. I'm looking at being able to just see what the link parameters are before anything else, otherwise I'm just peering at the LB1120 web pages, but that gives me a false sense of how it's actually doing, since there's no pretty graphs which display data over time.

**Comment by sofar** [comment]
Updated.

I have all the sensors I wanted working in homeassistant, and this is the last version of the patch I'm using.

**Comment by sofar** [comment]
BTW, just as a data point, the added sensors have almost all been really useful. I can see for instance when my modem goes roaming and is channel hopping a lot, and it's been useful to diagnose connection issues.

**Comment by amelchio** [comment]
I am not sure that I like the prospect of maintaining so many fields across several device types and firmware versions but let's see where it goes.

Before making a release, I want to update an example so it dumps all the fields. I expect to get it done during the weekend.

**Comment by amelchio** [comment]
This was finally added (with some modifications) to Home Assistant for the upcoming version 0.92.

**Pull request merged**
